connexta/admin-console

- PULL_REQUEST_TEMPLATE
- api/pom.xml
- pom.xml
- security/embedded-ldap-config-handler/pom.xml
- security/ldap-config-handler/pom.xml
- ui/pom.xml
Updates to latest release version of DDF and adds PR template.
@tbatie @peterhuffer @garrettfreibott 
Until this project is merged into DDF mainline, it will depend on the most current release version of DDF.
[DDF-2801](https://codice.atlassian.net/browse/DDF-2801)
N/A
> DDF-2801 Bump DDF dependencies to 2.10.0 and update to using shaded Spock jar.

- security/contextpolicy-config-handler/src/main/java/org/codice/ddf/admin/security/context/probe/AvailableOptionsProbeMethod.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/LdapTestingCommons.java
Adds a small amount of additional logging to LDAP wizard to assist in debugging/root cause analysis.
@tbatie @adimka 
Unit tests are sufficient.
N/A
N/A
> DDF-2773 Adds more logging to LDAP wizard.

- api/pom.xml
- api/src/test/groovy/org/codice/ddf/admin/api/configurator/OperationReportTest.groovy
- api/src/test/groovy/org/codice/ddf/admin/api/configurator/operations/AdminOperationTest.groovy
- api/src/test/groovy/org/codice/ddf/admin/api/configurator/operations/BundleConfigHandlerTest.groovy
- api/src/test/groovy/org/codice/ddf/admin/api/configurator/operations/FeatureConfigHandlerTest.groovy
- api/src/test/groovy/org/codice/ddf/admin/api/configurator/operations/ManagedServiceHandlerTest.groovy
- api/src/test/groovy/org/codice/ddf/admin/api/configurator/operations/PropertyConfigHandlerTest.groovy
- security/embedded-ldap-config-handler/pom.xml
- security/embedded-ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/embedded/EmbeddedLdapConfigurationHandlerTest.groovy
- security/ldap-config-handler/pom.xml
- security/ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/LdapConfigurationHandlerTest.groovy
Expands and moves LDAP unit tests.
@tbatie @adimka @peterhuffer 
CI build is sufficient.
N/A
N/A
> DDF-2773 Adds and moves some unit tests for LDAP.

- ui/src/main/webapp/adminTools/webContextPolicyManager/index.js
- ui/src/main/webapp/adminTools/webContextPolicyManager/styles.less
- ui/src/main/webapp/lib/admin-wizard/inputs.js
- ui/src/main/webapp/lib/components/MapDisplay.js
- ui/src/main/webapp/wizards/ldap/stages/bind-settings.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
- ui/src/main/webapp/wizards/sources/actions.js
- ui/src/main/webapp/wizards/sources/stages.js
- Manual URL input trims whitespace
- AutoFocus first input of each page
- Added "visible" attribute to inputs for conditionally displaying jsx input fields in place of ternary statements
- Edit button on WCPM no longer blocks highlighting
- Fix tooltip wording in WCPM
@djblue @tbatie @peterhuffer 
Make sure that the things listed above are correct.
> DDF-2773: Overall Frontend Usability and Style Improvements

- config-handler-router/src/main/java/org/codice/admin/router/ConfigurationHandlerRouterException.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/SourcesCommons.java
- pom.xml
Adds checkstyle plugin for repository.
@peterhuffer @adimka 
Full build. Additionally, it would be good to break something and ensure that checkstyle fails the build for it.
When the project was pulled out to its own repository and re-parented, the checkstyle plugin was missed. When it is promoted back into DDF, it will pick that up naturally.
N/A
> DDF-2773 Adds checkstyle plugin for repository.

- ui/src/main/webapp/adminTools/webContextPolicyManager/actions.js
1. WCPM whitelist bug where user could not save changes is fixed
2. WCPM bug where "/" was being reported as an invalid path was fixed
3. WCPM bug where context-path backend errors were not being displayed upon bin-save
@tbatie 
@coyotesqrl 
Ensure that "/" can be added and saved as a context path in the WCPM.
Ensure that the whitelist bin can be saved after adding/removing a path.
Ensure that context-paths errors reported from the backend are displayed upon save.
> DDF-2773: WCPM Save bug fix & error message fix

- .travis.yml
- travis_settings.xml
Adds deployment step to Travis.
@tbatie @djblue 
> DDF-2773 Adds Travis snapshot deploy

- .travis.yml
- travis_settings.xml
Snapshot and release deployment automated on main branches.
@djblue @tbatie 
> DDF-2773 Adds Travis deployment of SNAPSHOT and release artifacts

- ui/src/main/webapp/store.js
- ui/src/main/webapp/wizards/ldap/stages/actions.js
- ui/webpack.config.js
Clear LDAP query tool error messages.
@tbatie 
@peterhuffer 
Go through the LDAP wizard as normal, when you get to the query tool, try adding erroneous query parameters. Then try correct parameters and verify that the error messages have been cleared.
Currently the LDAP query tool doesn't clear error message when the user tries a new query. This PR updates the query tool to clear errors on a new query.
> Fix ldap query tool

- ui/.babelrc
- ui/.istanbul.yml
- ui/README.md
- ui/package.json
- ui/webpack.config.js
- ui/yarn.lock
Adds js code coverage.
@adimka  
Check the Travis logs and make sure code coverage tests are run as part of the ui build.
> DDF-2773: Added js code coverage.

- commons/pom.xml
- commons/src/main/java/org/codice/ddf/admin/commons/requests/RequestUtils.java
- commons/src/test/groovy/org.codice.ddf.admin.commons.requests/RequestUtilsTest.groovy
- federation/commons/src/main/java/org/codice/ddf/admin/commons/sources/SourceHandlerCommons.java
- federation/source-config-handlers/pom.xml
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/probe/DiscoverCswSourceProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/impl/test/ValidUrlTestMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/probe/DiscoverOpenSearchSourceProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/probe/DiscoverWfsSourceProbeMethod.java
- federation/source-config-handlers/src/test/groovy/org.codice.ddf.admin.sources/csw/CswSourceUtilsTest.groovy
- federation/source-config-handlers/src/test/groovy/org.codice.ddf.admin.sources/opensearch/OpenSearchSourceUtilsTest.groovy
- federation/source-config-handlers/src/test/groovy/org.codice.ddf.admin.sources/wfs/WfsSourceUtilsTest.groovy
- federation/source-config-handlers/src/test/resources/badOSQueryResponse.xml
- federation/source-config-handlers/src/test/resources/plainText.txt
Adds unit tests for all the futility functionality for all the Utils classes that the Source wizard depends on.
@coyotesqrl @garrettfreibott 
Clean install, check of all source auto and manual discovery
> DDF-2773 Unit tests for RequestUtils and all SourceUtils

- commons/src/main/java/org/codice/ddf/admin/commons/requests/RequestUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceUtils.java
Adds logging and JavaDoc improvements to the sources code
@tbatie @coyotesqrl @garrettfreibott 
Some logging duplicates error messages returned by the system to increase error visibility.
> DDF-2773 Add logging to sources classes, update and improve JavaDoc

- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/Configurator.java
- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/OperationReport.java
- configurator/configurator-impl/pom.xml
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/AdminOperation.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/BundleOperation.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfigValidator.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfiguratorImpl.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/FeatureOperation.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ManagedServiceOperation.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/Operation.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/OperationReportImpl.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/PropertyOperation.java
- configurator/configurator-impl/src/test/groovy/org/codice/ddf/admin/configurator/impl/ConfigValidatorTest.groovy
- configurator/configurator-impl/src/test/groovy/org/codice/ddf/admin/configurator/impl/OperationReportTest.groovy
Cleans and enhances the Configurator service
@tbatie @garrettfreibott 
Build/test/install and ensure that all functionality for reading/persisting still works.
[DDF-2825](https://codice.atlassian.net/browse/DDF-2825)
> DDF-2825 Code cleanup and validation for Configurator service

- ui/src/main/resources/index.html
See title.
@tbatie 
@coyotesqrl 
Open ui in IE and make sure comparability mode isn't set.
Without fix:
After fix:
> DDF-2773: Prevent IE from trying to use compatability mode.

- configurator/pom.xml
> DDF-2773 Fixes artifact name.

- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/impl/probe/DiscoverSourcesProbeMethod.java
@coyotesqrl @adimka 
Try to manually input a source URL and verify it works with no exceptions thrown.
> DDF-2773: Fix NPE from hostname when entering manual URL

- .travis.yml
Adds SonarQube integration and restructures travis.yml file
@djblue @adimka 
If the Travis CI build is successful on the PR, it should be merged. It will only run the integration against the master branch, not PRs from external forks. At that point, SonarQube should hopefully run successfully and the deployment of the snapshot artifacts should be verified to ensure no changes to the yaml file effected that.
N/A
N/A
> DDF-2773 Adds SonarQube integration

- pom.xml
- query/app/src/main/resources/features.xml
- query/common/src/main/java/org/codice/ddf/admin/common/services/ServicesCommons.java
- query/graphql/pom.xml
- query/security/common/src/main/java/org/codice/ddf/admin/security/common/fields/wcpm/services/PolicyManagerServiceProperties.java
- query/security/ldap/pom.xml
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/actions/commons/services/LdapLoginServiceProperties.java
- query/security/wcpm/pom.xml
- query/security/wcpm/src/main/java/org/codice/ddf/admin/security/wcpm/actions/discover/GetWhiteListContexts.java
- query/security/wcpm/src/main/java/org/codice/ddf/admin/security/wcpm/actions/persist/SaveWhitelistContexts.java
- query/security/wcpm/src/main/java/org/codice/ddf/admin/security/wcpm/commons/ContextPolicyServiceProperties.java
@coyotesqrl @peterhuffer 
WCPM graphql queries work.
These are some corrections being moved from itest research
> DDF-2773: Remove dependency on PolicyManager implementation

- configurator/configurator-impl/src/test/groovy/org/codice/ddf/admin/configurator/impl/PropertyConfigHandlerTest.groovy
- ui/package.json
Fixes issues with windows build.
@coyotesqrl 
@tbatie 
Do a full build on windows.
[DDF-2773:](https://codice.atlassian.net/browse/DDF-2773)
> DDF-2773: Fixed build issues for windows

- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/ConfigReader.java
- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/Configurator.java
- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/OperationReport.java
- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/Result.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfiguratorImpl.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/OperationReportImpl.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ResultImpl.java
- configurator/configurator-impl/src/test/groovy/org/codice/ddf/admin/configurator/impl/OperationReportTest.groovy
- security/embedded-ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/embedded/persist/DefaultEmbeddedLdapPersistMethodTest.groovy
Updates to reflect code review input from DDF contribution PR.
Full build and test. Manual test to ensure that configuration reads/writes still works correctly.
[DDF-2825](https://codice.atlassian.net/browse/DDF-2825)
N/A
> DDF-2825 Code review comments from DDF contribution PR.

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/actions/discover/LdapTestSettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/config/LdapSettingsField.java
Fixes the return value from LdapTest and removes an extraneous field from Ldap settings.
@peterhuffer @tbatie 
Full build and test
N/A
N/A
> DDF-2773 Small LDAP fixes

- .travis.yml
- itests/pom.xml
- itests/src/test/java/org/codice/ddf/admin/beta/ITestWebContextPolicyManager.java
- itests/src/test/resources/query/wcpm/SampleRequestVariables.json
- itests/src/test/resources/query/wcpm/mutation/SavePolicies.graphql
- itests/src/test/resources/query/wcpm/mutation/SaveWhiteListed.graphql
- itests/src/test/resources/query/wcpm/query/GetAuthTypes.graphql
- itests/src/test/resources/query/wcpm/query/GetPolicies.graphql
- itests/src/test/resources/query/wcpm/query/GetRealms.graphql
- itests/src/test/resources/query/wcpm/query/GetWhiteListed.graphql
- pom.xml
- snapshot-deploy.sh
Setup pax exam environment and wrote test that checks if schema was generated. Also wrote a portion of a test that pull data from the wcpm. Also bumped ddf version to 2.11.0-SNAPSHOT
@coyotesqrl  @peterhuffer 
CI passes
> DDF-2773: Initial itest environment setup

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/ServerGuesser.java
Minor cleanup
The changes are to comments and to an annotation specific to IJ. Nothing beyond a CI run is needed.
N/A
> DDF-2773 Minor cleanup and removal of two todos that have been OBE.

- pom.xml
- query/common/pom.xml
- query/common/src/main/java/org/codice/ddf/admin/common/fields/common/ContextPath.java
- query/graphql/pom.xml
- query/security/common/pom.xml
- query/security/wcpm/pom.xml
Inlines uri validation to remove dependency complexity.
@djblue @peterhuffer @tbatie 
Full CI run. Also, the WCPM should be tested to ensure it still validates correctly.
https://github.com/codice/ddf/pull/2062
> DDF-2773 Inlines uri validation and removes dependency on commons validator

- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/persist/SaveCswConfiguration.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/persist/SaveOpenSearchConfiguration.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/wfs/persist/SaveWfsConfiguration.java
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/csw/persist/SaveCswConfigurationTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/opensearch/persist/SaveOpenSearchConfigurationTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/wfs/persist/SaveWfsConfigurationTest.groovy
- Fix source feature startups to fail correctly
@tbatie @coyotesqrl
> DDF-2773: Fix source feature startups to fail correctly

- query/common/src/main/java/org/codice/ddf/admin/common/fields/common/ResponseField.java
- query/sources/common/src/main/java/org/codice/ddf/admin/sources/utils/RequestUtils.java
- Add content type field to ResponseField
@tbatie @coyotesqrl
> DDF-2773: Add content type to ResponseField

- pom.xml
- query/api/src/main/java/org/codice/ddf/admin/api/Events.java
- query/common/pom.xml
- query/common/src/main/java/org/codice/ddf/admin/common/fields/base/function/BaseFieldProvider.java
- query/common/src/main/java/org/codice/ddf/admin/common/poller/BaseEnumValuePoller.java
- query/common/src/main/java/org/codice/ddf/admin/common/services/ServiceCommons.java
- query/graphql/pom.xml
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/GraphQLTypesProviderImpl.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/servlet/ExtendedOsgiGraphQLServlet.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformCommons.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformEnum.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformInput.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformOutput.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformScalar.java
- query/graphql/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- query/graphql/src/test/groovy/org/codice/ddf/admin/graphql/test/GraphQLTransformationTest.groovy
- query/security/ldap/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- query/security/wcpm/src/main/java/org/codice/ddf/admin/security/wcpm/AuthTypesPoller.java
- query/security/wcpm/src/main/java/org/codice/ddf/admin/security/wcpm/RealmTypesPoller.java
- query/security/wcpm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
@coyotesqrl @djblue @blen-desta @garrettfreibott @peterhuffer 
- Ensure restarting a bundle with a FieldProvider does not cause exceptions. 
- LDAP realm should appear in WCPM UI after going through the LDAP wizard and no exceptions occur
- Turning off specific authentication type service, no exceptions should occur and the auth type should not be in the schema. Turning the auth type service back on refreshing schema with no exceptions and schema is updated.
- Install embedded ldap several times without any exceptions
> Fixed schema not refreshing when new enum values are registered or a new function is registered with a field provider

- query/sources/common/src/main/java/org/codice/ddf/admin/sources/services/CswServiceProperties.java
- query/sources/common/src/main/java/org/codice/ddf/admin/sources/services/OpenSearchServiceProperties.java
- query/sources/common/src/main/java/org/codice/ddf/admin/sources/services/WfsServiceProperties.java
- query/sources/common/src/main/java/org/codice/ddf/admin/sources/utils/SourceUtilCommons.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/discover/GetCswConfigurations.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/discover/GetOpenSearchConfigurations.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/wfs/discover/GetWfsConfigurations.java
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/csw/discover/DiscoverCswSourceSpec.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/test/SourceCommonsSpec.groovy
- Source test commons changes to make code more shareable
- Fix file typo
- Use generics when fetching currently configured source services to avoid casting
@tbatie @coyotesqrl @blen-desta 
The Groovy compiler compiles these methods to return objects, requiring casts in code reusing it.
> DDF-2773 Source test commons changes to make code more shareable

- .travis.yml
- query/app/pom.xml
> Added missing dependencies.

- admin-module/pom.xml
- artifact-size-enforcer/pom.xml
- pom.xml
- query/api/pom.xml
- query/app/pom.xml
- query/common/pom.xml
- query/graphql/pom.xml
- query/pom.xml
- query/security/common/pom.xml
- query/security/embeddedldap/pom.xml
- query/security/ldap/pom.xml
- query/security/pom.xml
- query/security/sts/pom.xml
- query/security/wcpm/pom.xml
- query/sources/common/pom.xml
- query/sources/impl/pom.xml
- query/sources/pom.xml
- query/utils/pom.xml
- ui/pom.xml
@peterhuffer @coyotesqrl @djblue 
Walk through all wizards
> DDF-2773: Changed version to 1.0.0-SNAPSHOT

- query/graphql/src/main/java/org/codice/ddf/admin/graphql/servlet/ExtendedOsgiGraphQLServlet.java
- query/graphql/src/test/groovy/org/codice/ddf/admin/graphql/test/GraphQLTransformationTest.groovy
- query/sources/common/src/main/java/org/codice/ddf/admin/sources/utils/SourceUtilCommons.java
> DDF-2773: Added max content length to requests (1.0.x)

- query/graphql/src/main/java/org/codice/ddf/admin/graphql/servlet/ExtendedOsgiGraphQLServlet.java
- query/graphql/src/test/groovy/org/codice/ddf/admin/graphql/test/GraphQLTransformationTest.groovy
- query/sources/common/src/main/java/org/codice/ddf/admin/sources/utils/SourceUtilCommons.java
@peterhuffer @coyotesqrl @blen-desta
- Walk through wizards and make sure request exceeding max content length is caught.
> DDF-2773: Added max content length to requests

- admin-module/pom.xml
- artifact-size-enforcer/pom.xml
- pom.xml
- query/api/pom.xml
- query/app/pom.xml
- query/common/pom.xml
- query/graphql/pom.xml
- query/pom.xml
- query/security/common/pom.xml
- query/security/embeddedldap/pom.xml
- query/security/ldap/pom.xml
- query/security/pom.xml
- query/security/sts/pom.xml
- query/security/wcpm/pom.xml
- query/sources/common/pom.xml
- query/sources/impl/pom.xml
- query/sources/pom.xml
- query/utils/pom.xml
- ui/pom.xml
> DDF-2773: Bump version to 1.1.0-SNAPSHOT

- query/graphql/src/main/java/org/codice/ddf/admin/graphql/servlet/request/DelegateRequest.java
Just adds some input stream methods 😄 
@tbatie @coyotesqrl
> Implemented additional ServletInputStream methods

- .travis.yml
- build.sh
- snapshot-deploy.sh
Enabled snapshot deploys for master branch.
@coyotesqrl 
@tbatie 
Travis build log.
> Enabled snapshot deploys for master branch.

- ui/src/main/resources/WEB-INF/classes/emptyfile
Empty file added to silence spurious log warning.
@peterhuffer @blen-desta @djblue 
Build and deploy KAR
> DDF-2773 [1.0.x] Adds an empty marker file to a web-only bundle

- ui/src/main/resources/WEB-INF/classes/emptyfile
Empty file added to silence spurious log warning.
@peterhuffer @blen-desta @djblue 
Build and deploy KAR
> DDF-2773 Adds an empty marker file to a web-only bundle

- ui/src/main/webapp/lib/admin-wizard/enhancers.js
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
Adds better error messages for attribute mapping stage.
@blen-desta 
Get to the LDAP attribute mapping stage and ensure that errors are displayed next to each mapping.
> Added better error messages for attribute mapping stage.

- ui/.istanbul.yml
- ui/src/main/webapp/lib/ddf-sources/index.js
- ui/src/main/webapp/wizards/sources/graphql/mutations.js
- ui/src/main/webapp/wizards/sources/graphql/queries.js
- ui/src/main/webapp/wizards/sources/stages/source-selection.js
Makes the sources wizard more extensible and fixes a small bug where the next button was not disabled.
@tbatie 
@peterhuffer 
Run through sources wizards and ensure that source discovery still works.
> Extensible sources wizard

- query/common/src/main/java/org/codice/ddf/admin/common/fields/base/scalar/StringField.java
- query/common/src/test/groovy/org/codice/ddf/admin/common/fields/base/scalar/StringFieldTest.groovy
- query/common/src/test/groovy/org/codice/ddf/admin/common/fields/common/HostnameFieldTest.groovy
- query/common/src/test/groovy/org/codice/ddf/admin/common/fields/common/UrlFieldTest.groovy
String will have an empty field error now when its value is white space, for example `'  '`.
@blen-desta @tbatie 
Unit tests
> DDF-2773: Add empty field error when string is whitespaces

- admin-module/pom.xml
- artifact-size-enforcer/pom.xml
- pom.xml
- query/api/pom.xml
- query/app/pom.xml
- query/common/pom.xml
- query/graphql/pom.xml
- query/pom.xml
- query/security/common/pom.xml
- query/security/embeddedldap/pom.xml
- query/security/ldap/pom.xml
- query/security/pom.xml
- query/security/sts/pom.xml
- query/security/wcpm/pom.xml
- query/sources/common/pom.xml
- query/sources/impl/pom.xml
- query/sources/pom.xml
- query/utils/pom.xml
- tests/commons/pom.xml
- tests/itests/pom.xml
- tests/pom.xml
- ui/pom.xml
@coyotesqrl @garrettfreibott @blen-desta @peterhuffer @djblue
> DDF-2773: Change version from 1.1.0-SNAPSHOT -> 1.2.0-SNAPSHOT

- pom.xml
@coyotesqrl @djblue @clockard @garrettfreibott
> DDF-2773: Update ddf version to 2.12.0-SNAPSHOT

- pom.xml
@coyotesqrl @djblue @clockard @garrettfreibott
> DDF-2773: Update ddf version to 2.11.2-SNAPSHOT

- ui/src/main/webapp/lib/admin-wizard/enhancers.js
- ui/src/main/webapp/lib/admin-wizard/inputs.js
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
- ui/src/main/webapp/wizards/ldap/stages/bind-settings.js
- ui/src/main/webapp/wizards/ldap/stages/configure-embedded-ldap.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/errors.js
- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
- ui/src/main/webapp/wizards/sources/stages/confirmation.js
Back port of https://github.com/connexta/admin-console/pull/161
@djblue @tbatie @garrettfreibott @blen-desta 
Ensure that error messages are being displayed correctly for LDAP wizard.
> [1.1.x] Fixed error message mapping to input fields

- ui/src/main/webapp/lib/admin-wizard/spec.js
> [1.1.x] Fix failing unit test.

- ui/src/main/webapp/lib/admin-wizard/enhancers.js
- ui/src/main/webapp/lib/admin-wizard/inputs.js
- ui/src/main/webapp/lib/admin-wizard/spec.js
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
- ui/src/main/webapp/wizards/ldap/stages/bind-settings.js
- ui/src/main/webapp/wizards/ldap/stages/configure-embedded-ldap.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/errors.js
- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
- ui/src/main/webapp/wizards/sources/stages/confirmation.js
Fixed error message mapping to input fields.
@tbatie 
Ensure that error messages are being displayed correctly for LDAP wizard.
> Fixed error message mapping to input fields.

- pom.xml
Fixes itests
@peterhuffer @blen-desta
> DDF-2773: DDF version bump 1.1.x

- Jenkinsfile
- dependency-check-maven-config.xml
- pom.xml
Adds a Jenkinsfile for supporting multi-branch pipeline builds
Pipeline will do the following:
1. Build/test origin branches on linux and windows
2. Build/test prs (incrementally) on linux and windows
3. Run OWASP on branches and prs
4. Run nodejs security on branches and prs
5. Deploy master and release branches
6. Run Sonar scans for branches and prs
7. Run coverity for master branch
In order to support incremental pr builds the gitflow-incremental-builder extension was added
In order to support owasp a profile was added
There may be some current outstanding issues with the component tests that need to be worked through before these builds will pass
@tbatie 
[DDF-3490](https://codice.atlassian.net/browse/DDF-3490)
> DDF-3490 Added Jenkins pipeline

- pom.xml
- query/common/src/main/java/org/codice/ddf/admin/common/PrioritizedBatchExecutor.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceInfoField.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/persist/UpdateOpenSearchConfiguration.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/AdminSecurityIT.java
- ui/README.md
- ui/src/main/webapp/lib/admin-wizard/index.js
- ui/src/main/webapp/security/wcpm/components.js
- ui/src/main/webapp/security/wcpm/editable-list.js
- ui/src/main/webapp/security/wcpm/editable-list.spec.js
- ui/src/main/webapp/security/wcpm/index.js
- ui/src/main/webapp/store.js
This PR fixes some miscellaneous typos.
@garrettfreibott @peterhuffer @blen-desta
Full build
[DDF-2824](https://codice.atlassian.net/browse/DDF-2824)
> [1.1.x] DDF-2824 Fixed some miscellaneous typos

- pom.xml
- query/common/src/main/java/org/codice/ddf/admin/common/PrioritizedBatchExecutor.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceInfoField.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/persist/UpdateOpenSearchConfiguration.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/AdminSecurityIT.java
- ui/README.md
- ui/src/main/webapp/lib/admin-wizard/index.js
- ui/src/main/webapp/security/wcpm/components.js
- ui/src/main/webapp/security/wcpm/editable-list.js
- ui/src/main/webapp/security/wcpm/editable-list.spec.js
- ui/src/main/webapp/security/wcpm/index.js
- ui/src/main/webapp/store.js
____
Port of https://github.com/connexta/admin-console/pull/179
@peterhuffer @blen-desta @oconnormi @garrettfreibott 
[DDF-2824](https://codice.atlassian.net/browse/DDF-2824)
> DDF-2824 Fixed some miscellaneous typos

- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
____
Port of https://github.com/connexta/admin-console/pull/180
@djblue @peterhuffer @garrettfreibott
> DDF-2773 Added port validation in the LDAP Wizard before submitting GraphQL query

- Jenkinsfile
Skips running itests in CI. These will be re-enabled once working
@tbatie @mcalcote
> DDF-3490 Temporariliy disabling itests in CI builds

- Jenkinsfile
Fixes a typo in the jenkinsfile
> Fixing incorrect quoting in jenkinsfile

- ui/src/main/webapp/wizards/sources/stages/discovery.js
Fixes error not displaying when discovering sources by URL.
@garrettfreibott @tbatie @djblue 
Input an invalid URL in the source discovery by URL stage and verify an error is displayed to the end user.
> [1.1.x] DDF-2773 Fix source discovery by URL stage error display

- query/app/src/main/resources/features.xml
- ui/pom.xml
- ui/src/main/resources/WEB-INF/web.xml
@peterhuffer 
@tbatie 
- Build
- Deploy
- Ensure UI assets are loaded with gzip enabled
[DDF-2803](https://codice.atlassian.net/browse/DDF-2803)
> [1.1.x] Enables gzip

- query/app/src/main/resources/features.xml
- ui/pom.xml
- ui/src/main/resources/WEB-INF/web.xml
> Enables gzip

- pom.xml
- query/app/src/main/resources/features.xml
- query/graphql/pom.xml
> Fixed conflicting package versions exported by DDF [1.1.x]

- query/app/src/main/resources/features.xml
- query/graphql/pom.xml
Fixed conflicting package versions exported by DDF
@peterhuffer @djblue @blen-desta 
A quick walkthrough all the wizards should suffice.
> Fixed conflicting package versions exported by DDF

- pom.xml
Adds the suppression files from ddf to the admin console suppressions
@coyotesqrl  @peterhuffer 
CI pass.
> Added DDF OWASP suppressions

- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
Fixes a bug that didn't map errors correctly when deleting rows in LDAP attribute mapping stage
@figliold @garrettfreibott @djblue 
In the attribute mapping stage, add claims mapping entries that are valid and invalid. After hitting next, error icons should appear next to invalid rows. Ensure after deleting different rows, the various errors are still on the correct rows.
> Fix Error Mapping in LDAP Attribute Mapping Stage

- README.md
- pom.xml
See PR title.
@coyotesqrl @peterhuffer 
N/A
> Updated README and removed the word beta from various places

- pom.xml
- query/app/src/main/resources/features.xml
- Updates DDF version to latest
- Removes feature bundle dependency on catalog-core-api
@tbatie @coyotesqrl @blen-desta 
> DDF-2773 Updates DDF version to latest

- dependency-check-maven-config.xml
> Suppressed jgraphx vulnerability

- query/app/src/main/resources/features.xml
- Remove sources feature dependency on catalog-core-api
@tbatie @coyotesqrl @blen-desta 
> DDF-2773 Remove sources feature dependency on catalog-core-api

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/persist/CreateLdapConfiguration.java
Adds validation to CreateLdapConfiguration for STS claims.
@tbatie @figliold @coyotesqrl
[DDF-3717](https://codice.atlassian.net/browse/DDF-3717)
> Add STS claims validation

- tests/itests/pom.xml
The security-services-app was removed in https://github.com/codice/ddf/pull/2896
@peterhuffer @emmberk 
A successful full build
> DDF-3739: Remove dead feature file reference

- tests/itests/pom.xml
This feature file was removed in https://github.com/codice/ddf/pull/3300
@blen-desta  @peterhuffer @figliold 
Full build pass
> DDF-2773: Remove dead admin feature file reference

- ui/src/main/webapp/wizards/sources/stages/discovery.js
Port of 2cae2d3699024bee051bfdbad094f50fbf2ab30b
@garrettfreibott @tbatie @djblue
Input an invalid URL in the source discovery by URL stage and verify an error is displayed to the end user.
> DDF-2773 Fix source discovery by URL stage error display

- pom.xml
- tests/commons/src/main/resources/features.xml
@tbatie @emmberk @peterhuffer 
Full test with downstream project to ensure that libraries and permissions are working correctly.
[DDF-3920](https://codice.atlassian.net/browse/DDF-3920)
> DDF-2773 Upgrades DDF to 2.13.x and corresponding cxf libraries.

- query/app/src/main/resources/features.xml
The error feature was broken out into `error-api` and `error-impl` in https://github.com/codice/ddf/pull/3621/files#diff-8705ee15cd7d549d5ca8878b1d9ff8ecR65 This is updating the feature file to account for that fix.
@coyotesqrl @djblue  @peterhuffer 
Kar successfully hot deploys
> Fixed the error feature to point to error-impl feature instead

- query/app/src/main/resources/features.xml
The error feature was broken out into `error-api` and `error-impl` in https://github.com/codice/ddf/pull/3621/files#diff-8705ee15cd7d549d5ca8878b1d9ff8ecR65 This is updating the feature file to account for that fix.
@coyotesqrl @djblue  @peterhuffer 
Kar successfully hot deploys
> [1.2.x] Fixed the error feature to point to error-impl feature instead

- pom.xml
- query/sources/common/pom.xml
Updated POMs based on changes for https://github.com/codice/ddf/pull/3842
@coyotesqrl @tbatie @blen-desta 
Full build.
[DDF-2985](https://codice.atlassian.net/browse/DDF-2985)
> DDF-2985 Declare dependencies that were transitive

- query/app/src/main/resources/features.xml
Adds bundle to sources feature.
@clockard @tbatie @blen-desta 
Drop the KAR into DDF `deploy` directory and verify it installs correctly.
Oversight of https://github.com/connexta/admin-console/commit/fe6c21f80ada5739e6a6c1749c9331f1995180ac
[DDF-2985](https://codice.atlassian.net/browse/DDF-2985)
> DDF-2985 Fix admin-query-sources-impl install

- pom.xml
- query/security/wcpm/src/test/groovy/org/codice/ddf/admin/security/wcpm/persist/WcpmTestingCommons.groovy
See title
@peterhuffer 
@clockard 
Wizards run as expected.
> Upgrade to DDF 2.13.3

- pom.xml
Added over-ride to prevent GIB from causing a PR build to fail, when the git context is messed up or cannot be calculated
@blen-desta 
@oconnormi 
Perform a PR build
Fixes reproducible errors while trying to use GIB to build PR-219: https://jenkins.codice.org/job/admin-console/job/PR-219/5/display/redirect
> Ignore GIB failures

- features/admin-query/src/main/feature/feature.xml
- pom.xml
- query/graphql/pom.xml
- query/graphql/src/main/java/org/codice/ddf/graphql/FunctionDataFetcherException.java
- tests/itest-commons/src/main/java/org/codice/ddf/admin/graphql/test/GraphQlHelper.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/request/LdapRequestHelper.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/request/WcpmRequestHelper.java
@coyotesqrl @tbatie @blen-desta @bakejeyner 
Since a lot of this is within itests, <strike>that are currently disabled</strike> I debugged the admin-console at the constructor of FunctionDataFetcherException, tried to add an invalid ldap and logged the resulting json error to make sure it looked good. 
That and a good CI should be enough. 
(Since I test have been re-enabled a successful CI should suffice). 
[DDF-4261](https://codice.atlassian.net/browse/DDF-4261)
> DDF-4261 Replacing Boon with Gson

- pom.xml
See title
@coyotesqrl @peterhuffer @clockard 
Wizards work as expected
> Upgrade ddf version to 2.13.4 & karaf to 4.2.1

- query/graphql/src/main/resources/OSGI-INF/blueprint/blueprint.xml
remove DosFilter as a workaround until we can figure out wh pax-web indiscriminately adding filters to other servlet contexts
> remove DosFilter

- ThreatDragonModels/AdminWizards.json
Adds OWASP Threat Dragon Threat Model
@tbatie 
@coyotesqrl 
Verify against the old Threat Model. Note: some threats were removed/modified since they are not applicable.
To view use: https://threatdragon.org
> Added OWASP Threat Dragon Threat Model

- pom.xml
- query/graphql/src/main/resources/OSGI-INF/blueprint/blueprint.xml
> remove DosFilter in 1.2.x

- features/admin-query/pom.xml
- features/pom.xml
- features/testing/pom.xml
- pom.xml
- tests/pom.xml
Fixes the full build.
@blen-desta @tbatie @peterhuffer 
Run a full build locally on an empty m2.
> Fix feature itests

- Jenkinsfile
- dependency-check-maven-config.xml
- query/app/src/main/resources/features.xml
- query/graphql/pom.xml
- Upgrades graphql-java-annotations to remove lombok
@tbatie @clockard @paouelle
- Test setting up a source
- Test setting up ldap (see me for ldap server details)
- Test modifying a policy through the policy UI.
> Remove lombok and upgrade graphql annotations

- query/common/src/main/java/org/codice/ddf/admin/common/fields/base/scalar/BooleanField.java
- query/common/src/main/java/org/codice/ddf/admin/common/fields/base/scalar/LongField.java
- query/common/src/test/groovy/org/codice/ddf/admin/common/fields/base/BaseObjectFieldTest.groovy
- query/common/src/test/java/org/codice/ddf/admin/common/fields/test/TestFieldProvider.java
- query/common/src/test/java/org/codice/ddf/admin/common/fields/test/TestObjectField.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformScalar.java
- query/graphql/src/test/groovy/org/codice/ddf/admin/graphql/test/GraphQLTransformationTest.groovy
- query/graphql/src/test/resources/queries/GetBaseFieldTypesQuery
- query/graphql/src/test/resources/queries/MessagePathsQuery
- query/graphql/src/test/resources/queries/MissingRequiredArgumentQuery
- query/graphql/src/test/resources/queries/MissingRequiredInnerFieldsArgumentQuery
- query/graphql/src/test/resources/queries/MultipleArgumentsQuery
- query/graphql/src/test/resources/queries/SatisfiedRequiredFieldsQuery
- Adds support for Long scalar type
- Add description to BooleanField ctor
@tbatie @kcover @clockard 
CI build.
> Add support for Long scalar type

- Jenkinsfile
- pom.xml
- Removes no longer supported sonarcloud option `sonar.analysis.mode`
- Removes no longer available nodejs security scanning service
@tbatie @coyotesqrl @blen-desta 
CI build.
> Pipeline fixes

- Jenkinsfile
@shaundmorris @blen-desta @mcalcote @LinkMJB
> Ignore Windows stage in the pipeline

- query/common/src/main/java/org/codice/ddf/admin/common/fields/base/scalar/LongField.java
- query/common/src/test/groovy/org/codice/ddf/admin/common/fields/base/BaseObjectFieldTest.groovy
- query/common/src/test/java/org/codice/ddf/admin/common/fields/test/TestFieldProvider.java
- query/common/src/test/java/org/codice/ddf/admin/common/fields/test/TestObjectField.java
- query/graphql/src/main/java/org/codice/ddf/graphql/transform/GraphQLTransformScalar.java
- query/graphql/src/test/groovy/org/codice/ddf/graphql/GraphQLTransformationTest.groovy
- query/graphql/src/test/resources/queries/GetBaseFieldTypesQuery
- query/graphql/src/test/resources/queries/MessagePathsQuery
- query/graphql/src/test/resources/queries/MissingRequiredArgumentQuery
- query/graphql/src/test/resources/queries/MissingRequiredInnerFieldsArgumentQuery
- query/graphql/src/test/resources/queries/MultipleArgumentsQuery
- query/graphql/src/test/resources/queries/SatisfiedRequiredFieldsQuery
- Port of https://github.com/connexta/admin-console/pull/239
@tbatie @clockard @kcover
CI build.
> Add support for Long scalar type (#239)

- Jenkinsfile
> Run the master build weekly

- Jenkinsfile
upgrades the Maven Version used in the pipeline from 3.5.2 to maven-latest which is currently defined as 3.6.3 in Jenkins tool configuration
@LinkMJB 
@shaundmorris 
Just run the pipeline. The following test was run against my fork on prod Jenkins
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/admin-console-tm/job/master/
> BR-42 Upgrade to maven-latest

- Jenkinsfile
Removed the Coverity stage in Quality Analysis
@LinkMJB 
@shaundmorris 
See the test run in Prod Jenkins
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/admin-console-tm/job/master/
No longer using Coverity
BR-105 Remove Coverity testing stage
> BR-105 Remove Coverity testing stage

- pom.xml
Upgrade Dependency Check to 6.0.5 as breaking changes were introduced as of 6.0.x. 
@shaundmorris 
@stustison 
Run the build on the CX Jenkins, the owasp stage should not fail with SQL errors
> BR-158 Upgrade Dependency Check plugin to 6.0.5
