connexta/admin-console

- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/ServerGuesser.java
Exception thrown by `ServerGuesser` when no rootDomainNamingContext attribute found in base object search.
This can occur if ActiveDirectory is misconfigured, or if the AD profile is chosen for a non-AD server.
Confirms first that the attribute exists before attempting to extract its value.
@garrettfreibott @adimka @peterhuffer 
Select ActiveDirectory as the server type but point to a running Embedded LDAP (or other LDAP type externally if one is available) and step forward to the Directory Structure stage. If no exception is thrown, the stage should display correctly.
N/A
N/A
> DDF-2773 Fixes exception thrown by ServerGuesser

- api/src/main/java/org/codice/ddf/admin/api/configurator/operations/ManagedServiceOperation.java
- api/src/test/groovy/org/codice/ddf/admin/api/ManagedServiceHandlerTest.groovy
Fixes the case where an invalid/unknown pid will result in a silent pass. Instead, will report a transaction failure.
@tbatie @peterhuffer @adimka 
Unit test should be sufficient. Otherwise, calling the `Configurator.deleteManagedService()` method with an unknown managed service pid (e.g. with a factory pid instead of the pid of a managed instance) and attempting to commit should result in a transaction failure.
N/A
N/A
> DDF-2773 Ensures that an invalid PID (one with no known factory PID) will not incorrectly report success on deletion.

- config-handler-router/pom.xml
- config-handler-router/src/main/java/org/codice/admin/router/ConfigurationHandlerRouter.java
- config-handler-router/src/main/java/org/codice/admin/router/ConfigurationHandlerRouterException.java
- config-handler-router/src/test/groovy/org/codice/admin/router/ConfigurationHandlerRouterTest.groovy
- Refactor `ConfigurationHandlerRouter` methods
- Add unit tests for `ConfigurationHandlerRouter`
@coyotesqrl @tbatie @adimka 
Test:
Full build. Verify source and LDAP wizard functionality, and `/capabilities`, `/capabilites/{handlerId}`, and `/configurations/{handlerId}` all work as expected.
> Add unit tests for ConfigurationHandlerRouter

- security/ldap-config-handler/pom.xml
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/LdapConfigurationHandler.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/AttributeMappingTestMethod.java
- security/ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/test/AttributeMappingTestMethodTest.groovy
If any of the selected attributes to be mapped is not present on at least one user in the base user directory, a warning will be reported.
@garrettfreibott @tbatie @djblue 
* Pointing the a running embedded ldap (or any running external server), create an attribute store (with or without it being a login server).
* Step through to the STS Attribute Mapping stage.
* Select or type in a bad value for attribute, one that is not present on any users in the user directory
* *Until message reporting is fixed on the front-end for this page*, 
* Using browser tools, inspect and watch the network panel
* Ensure that an invalid field message is reported
* Fix the attribute(s) that are incorrect with valid ones that can be found on at least one user
* Ensure that you can move forward to the final …
> DDF-2773 Adds attribute validation to the LDAP STS Attribute mapping stage

- ui/src/main/webapp/home/actions.js
- ui/src/main/webapp/home/index.js
- ui/src/main/webapp/home/reducer.js
- ui/src/main/webapp/home/styles.less
- ui/src/main/webapp/lib/components/Spinner.js
- ui/src/main/webapp/lib/components/Stage.js
- ui/src/main/webapp/lib/components/styles.less
- ui/src/main/webapp/lib/system-usage/Banners.js
- ui/src/main/webapp/reducer/index.js
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
- ui/src/main/webapp/wizards/ldap/stages/bind-settings.js
- ui/src/main/webapp/wizards/ldap/stages/configure-embedded-ldap.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
- Added a spinner to the config panels when a delete request is sent.
- Moved actions & async calls to actions.js file and reducer logic to reducer.js file to match other directory structures
- Some minor cleanup and refactoring
@djblue @tbatie @coyotesqrl 
Before:
After clicking delete:
After delete:
Error message examples on Sources & LDAP tiles:
Testing:
Make create a source, delete it, and make sure the spinner appears while the request to delete is sent. Since the home page code was refactored, also keep an eye out for any functionality on that screen that might have been Affected. All links and config/ldap polling should be fine.
Testing error reporting is a bit trickier since an error needs to occur on delete in the backend. I've been using a proxy to modify the outgoing request so …
> DDF-2773: Add Progress Icon on Delete & Error Messages to Homepage Configs

- api/src/main/java/org/codice/ddf/admin/api/config/sources/CswSourceConfiguration.java
- api/src/main/java/org/codice/ddf/admin/api/config/sources/OpenSearchSourceConfiguration.java
- api/src/main/java/org/codice/ddf/admin/api/config/sources/SourceConfiguration.java
- api/src/main/java/org/codice/ddf/admin/api/config/sources/WfsSourceConfiguration.java
- api/src/main/java/org/codice/ddf/admin/api/handler/commons/SourceHandlerCommons.java
- api/src/main/java/org/codice/ddf/admin/api/validation/SourceValidationUtils.java
- api/src/test/groovy/org/codice/ddf/admin/api/validation/SourceValidationUtilsTest.groovy
- federation/source-config-handlers/pom.xml
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/persist/CreateCswSourcePersistMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/probe/CswConfigFromUrlProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/probe/DiscoverCswSourceProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/test/SourceNameExistsCswTestMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/impl/SourceConfigurationHandlerImpl.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/impl/probe/DiscoverSourcesProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/impl/test/SourceNameExistsTestMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/persist/CreateOpenSearchSourcePersistMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/probe/DiscoverOpenSearchSourceProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/probe/OpenSearchConfigFromUrlProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/test/SourceNameExistsOpenSearchTestMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/persist/CreateWfsSourcePersistMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/probe/DiscoverWfsSourceProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/probe/WfsConfigFromUrlProbeMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/test/SourceNameExistsWfsTestMethod.java
- federation/source-config-handlers/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- ui/src/main/webapp/wizards/sources/actions.js
- Cannot have duplicate source names anymore
- Error will appear if attempting to create a duplicate source name
- Unit tests
- The SourceNameExists TestMethod will be called during a Persist for a specific Source Configuration Handler.
@tbatie @adimka @coyotesqrl 
Manual test:
Create a source.
Attempt to create another source with same name. Observe error message.
Test this for CSW, WFS, and OpenSearch.
> DDF-2773: Fix duplicate source names being allowed

- app/pom.xml
- app/src/main/resources/features.xml
Ensures that the GSON jar is included in the KAR and fixes packaging on app so only the KAR is created, not the additional jar.
Apply changes from https://github.com/codice/ddf/pull/1721 to the `$KARAF_HOME/etc/org.ops4j.pax.url.mvn.cfg` file in your DDF distribution, build this project, and hot deploy the resulting KAR.
N/A
N/A
> DDF-2773 Small fixes to make KAR hot-deployable.

- api/src/main/java/org/codice/ddf/admin/api/validation/SourceValidationUtils.java
- api/src/test/groovy/org/codice/ddf/admin/api/validation/SourceValidationUtilsTest.groovy
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/persist/CreateLdapConfigMethod.java
- Fixes empty attributeMappings check when only creating LDAP Authentication Source
- Fix empty string passing Source Name Exists test method.
- Add unit test for emptry string source name.
@coyotesqrl @adimka 
Configure all available LDAP types. Authentication, Attribute Store, Authentication and Attribute Store.
Passing unit tests for SourceValidationUtils.
> DDF-2773: Fix error when creating LDAP Authentication Source

- api/src/main/java/org/codice/ddf/admin/api/services/PolicyManagerServiceProperties.java
- Fixes comparison of authentication types
- Maintains order of authentication types
@tbatie @garrettfreibott 
Ensure WCPM bins are collapsing if they have the same policies. Create new policies that should collapse.
> DIB-2773: Fix WCPM policy collapse

- api/src/main/java/org/codice/ddf/admin/api/configurator/Configurator.java
- api/src/main/java/org/codice/ddf/admin/api/validation/SourceValidationUtils.java
- pom.xml
Javadocs will be generated for all builds. Docs and sources attached to all releases.
@peterhuffer @tbatie 
Run a build and ensure docs are generated.
N/A
N/A
> DDF-2773 Fixes javadoc errors and enables javadoc generation

- .travis.yml
- snapshot-deploy.sh
Conditionally deploy to nexus if the codice credentials are available.
@coyotesqrl 
@tbatie 
The PR build should not try to deploy snapshot artifacts to nexus.
Currently, travis will always try to deploy to nexus after a successful build, this adds a condition that to deploy, the `$CODICE_PASSWORD` environment variable should be available, which is not available for PR builds.
> DDF-2773: Added conditional snapshot deploy for travis.

- api/src/main/java/org/codice/ddf/admin/api/config/Configuration.java
- api/src/main/java/org/codice/ddf/admin/api/handler/ConfigurationMessage.java
- api/src/main/java/org/codice/ddf/admin/api/services/LdapLoginServiceProperties.java
- security/ldap-config-handler/pom.xml
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/persist/CreateLdapConfigMethod.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/LdapTestingCommons.java
- If an LDAP configuration already exists, a warning will be returned on the confirm LDAP settings stage.
@adimka @coyotesqrl 
Send a request with `ignoreWarnings` set to `false`. Should produce and warning and stop configuration from persisting. see me or @garrettfreibott on how to do this.
> DDF-2773: Adds warning when creating ldap config

- ui/src/main/webapp/home/index.js
**NOTE**: this PR directly utilizes a refactored component from PR #28 - please only review the most recent commit on this PR.
Adds a confirm dialog to the Sources and LDAP home screen configs. Also centers the delete buttons because they look a bit cleaner that way with the confirmation dialog.
@djblue 
Click the delete buttons and make sure that a confirmation dialog appears. Confirm that the "Yes" and "No" buttons delete and cancel the delete respectively.
Spinner is displayed after pressing "Yes".
> DDF-2773: Confirm on delete configs (dependency on PR #28)

- ui/src/main/webapp/lib/admin-wizard/actions.js
- ui/src/main/webapp/lib/admin-wizard/index.js
- ui/src/main/webapp/lib/admin-wizard/reducer.js
- ui/src/main/webapp/lib/components/ActionMessage.js
- ui/src/main/webapp/lib/components/Message.js
- ui/src/main/webapp/lib/components/styles.less
- ui/src/main/webapp/reducer/index.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
**NOTE**: this PR builds off of changes from PR #28 - please only review the most recent commit on this PR.
Adds a message when ONLY warnings are returned from the backend on the directory structure page of the LDAP wizard that allows the user to ignore the warnings and continue to the next stage. The message will only remain visible so long as no other fields have been changed and the user has not navigated away from the page to ensure that the user does not accidentally modify a field and then be allowed to skip validation.
@tbatie @djblue @peterhuffer 
Make sure that if warnings ONLY are returned from the backend, the message appears and the user can continue anyways. Also test that if any fields are modified or if the stage changes, the message goes away and the user must re-validate …
> DDF-2773: LDAP directory page skippable warnings (dependency on PR #28)

- ui/src/main/webapp/lib/admin-wizard/actions.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
NOTE: this PR directly utilizes a component created in PR #30 - please only review the most recent commit on this PR.
If an identical LDAP configuration already exists, a warning message will be displayed and the user has the option to ignore errors and force a persist
@coyotesqrl @adimka 
Add 2 identical LDAP configs and ensure that a skippable error is displayed when the second config tries to persist. Ensure that pressing the "Ignore and Save >" button will continue to the finished screen and the configuration is saved.
> DDF-2773: Skippable LDAP Config Warnings (Dependency on PR #30)

- app/pom.xml
- pom.xml
- security/contextpolicy-config-handler/src/main/java/org/codice/ddf/admin/security/context/persist/EditContextPolicyMethod.java
- ui/src/main/webapp/adminTools/webContextPolicyManager/actions.js
- ui/src/main/webapp/adminTools/webContextPolicyManager/reducer.js
- ui/src/main/webapp/reducer/index.js
Protects the root context (/) from being deleted either by editing a context definition or by deleting one.
@tbatie @djblue 
1. Confirm that no regressions have been introduced (contexts can be added/edited/removed still).
2. Attempt to delete the root context; an error should display preventing the deletion.
3. Add a second context path to the entry that contains the root context; this should succeed.
4. Attempt to delete this entry; an error should display preventing the deletion.
5. Edit this entry, attempting to remove the root path but leaving the second; an error should display preventing the deletion.
6. Edit this entry, attempting to remove the secondary path; this should succeed.
N/A
> DDF-2773 In admin console, prevents root web context from being deleted

- commons/src/main/java/org/codice/ddf/admin/commons/requests/RequestUtils.java
- commons/src/test/groovy/org.codice.ddf.admin.commons.requests/RequestUtilsTest.groovy
Adds unit tests ensuring we're closing all closable resources via all branches of logic.
@tbatie @coyotesqrl @garrettfreibott 
These tests will ensure we don't make future changes that result in us not closing resources.
- [] Documentation Updated
> DDF-2773 Add unit tests to verify HttpClients and HttpResponses are always closed

- api/pom.xml
- api/src/main/java/org/codice/ddf/admin/api/config/context/ContextPolicyBin.java
- api/src/main/java/org/codice/ddf/admin/api/validation/SecurityValidationUtils.java
- api/src/test/groovy/org/codice/ddf/admin/api/validation/SecurityValidationUtilsTest.groovy
- security/contextpolicy-config-handler/src/main/java/org/codice/ddf/admin/security/context/probe/AvailableOptionsProbeMethod.java
Uses case-insensitive comparisons to validate realms and authentication methods; passes correctly cased values to underlying configuration regardless of input.
@tbatie @adimka 
1. Ensure the WCPM correctly loads against DDF 2.11.0-SNAPSHOT (defaults are not set to IDP).
2. Ensure that the values persisted to the underlying configuration match the case expected.
3. Test a post, circumventing the UI, to ensure that incorrectly cased inputs for realm and authentication are accepted as valid but persisted correctly.
N/A
N/A
> DDF-2773 Makes validation of realms and authentication methods case-insensitive

- api/src/main/java/org/codice/ddf/admin/api/handler/report/Report.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/AttributeMappingTestMethod.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/DirectoryStructTestMethod.java
Switch is for whole subtree.
Also cleans up a little unrelated, inefficient code.
@garrettfreibott @adimka 
Ensure that creating LDAP auth & attribute store works. Specifically that the directory struct stage works correctly.
N/A
N/A
> DDF-2773 Switches out non-standard 'subordinates' LDAP search scope

- federation/commons/src/main/java/org/codice/ddf/admin/commons/sources/SourceHandlerCommons.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/impl/probe/DiscoverSourcesProbeMethod.java
- ui/src/main/webapp/wizards/sources/stages/discovery.js
Adds IP address support to the hostname field for source discovery.
@tbatie @coyotesqrl @garrettfreibott 
Confirm discovery via IP address is possible, (ideally with loopback and a remote source)
> DDF-2773 Sources wizard should support discovery by IP address

- admin-module/pom.xml
- admin-module/src/main/java/org/codice/admin/module/AdminConfModule.java
- admin-module/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- app/pom.xml
- app/src/main/resources/features.xml
- config-handler-router/pom.xml
- pom.xml
- ui/src/main/resources/index.html
- ui/src/main/webapp/app.js
- ui/src/main/webapp/lib/components/styles.less
- ui/src/main/webapp/wizards/sources/styles.less
- Now pluggable Admin Console (iframed into AdminUI). 
- Title removed from header bar
- Also updates Spark to latest version (2.5.5).
@tbatie 
Build and deploy into a DDF instance. Ensure that a new link appears in the sidebar nav and that it opens up an iframe with the console inside it. Confirm that the console's functionality is unaffected.
N/A
> DDF-2773 Creates new AdminModule to plug the Beta Console into AdminUI

- ui/src/main/webapp/lib/components/Backdrop.js
Very small change - fixes backdrop height in full-screen view. Full screen needed min-height, not just height.
@djblue @coyotesqrl 
Does not extend past bottom in Admin UI:
Extends all the way to bottom of elements in full-screen:
> DDF-2773: Fixed FullScreen Backdrop Height

- ui/src/main/webapp/lib/system-usage/Modal.js
System Usage modal only shows up when not iframe'd. The admin UI should display the modal already, so a second modal is unnecessary.
@coyotesqrl @tbatie
> DDF-2773: Modal only shows when not in iFrame

- ui/src/main/resources/index.html
DDF master and DDF 2.10.x have different paths to the frameresizer script; this allows for deployment to either version.
@djblue @garrettfreibott 
Deploy to DDF 2.10.x and DDF 2.11.x; ensure that the iframed console appears and scrolls correctly.
> DDF-2773 Supports iframeresizer in either of its two source locations

- ui/src/main/webapp/lib/admin-app-bar/index.js
- ui/src/main/webapp/lib/react-swatch/index.js
Removes react-color from the production build and imports less of react-color in dev-mode.
@tbatie 
@djblue 
@peterhuffer
> DDF-2773: Removes react-color from prod & optimizes dev import

- api/src/main/java/org/codice/ddf/admin/api/services/LdapClaimsHandlerServiceProperties.java
- api/src/test/groovy/org/codice/ddf/admin/api/services/LdapClaimsHandlerServicePropertiesTest.groovy
@adimka @tbatie @peterhuffer 
Deploy and create an LDAP config. It should save and any saved configurations should be displayed on the home page.
> DDF-2773 Resolve validation issue with property paths when reading configurations

- api/src/main/java/org/codice/ddf/admin/api/services/LdapClaimsHandlerServiceProperties.java
- api/src/main/java/org/codice/ddf/admin/api/services/PolicyManagerServiceProperties.java
- api/src/main/java/org/codice/ddf/admin/api/validation/SourceValidationUtils.java
- api/src/test/groovy/org/codice/ddf/admin/api/services/LdapClaimsHandlerServicePropertiesTest.groovy
- api/src/test/groovy/org/codice/ddf/admin/api/validation/SourceValidationUtilsTest.groovy
- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/ConfigReader.java
- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/Configurator.java
- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/ConfiguratorFactory.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfiguratorFactoryImpl.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfiguratorImpl.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/test/SourceNameExistsCswTestMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/test/SourceNameExistsOpenSearchTestMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/test/SourceNameExistsWfsTestMethod.java
- security/contextpolicy-config-handler/src/main/java/org/codice/ddf/admin/security/context/ContextPolicyManagerHandler.java
- security/contextpolicy-config-handler/src/main/java/org/codice/ddf/admin/security/context/probe/AvailableOptionsProbeMethod.java
- security/embedded-ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/embedded/EmbeddedLdapConfigurationHandler.java
- security/embedded-ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/embedded/EmbeddedLdapConfigurationHandlerTest.groovy
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/LdapConfigurationHandler.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/probe/SubjectAttributeProbe.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/AttributeMappingTestMethod.java
- security/ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/probe/SubjectAttributeProbeTest.groovy
- security/ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/test/AttributeMappingTestMethodTest.groovy
This more clearly delineates the operation/transaction code, separating it out from the reader helper methods.
@tbatie @peterhuffer @adimka 
Full build/test and short heroing of all three wizards.
As the Configurator is currently under review for contribution to DDF, suggested changes being made there are being reflected back here as this project is the only one exercising its functionality.
See [this PR](https://github.com/codice/ddf/pull/1806) for more details.
[DDF-2825](https://codice.atlassian.net/browse/DDF-2825)
N/A
> DDF-2825 Extracts configuration reader functionality from Configurator interface

- artifact-size-enforcer/pom.xml
- artifact-size-enforcer/src/main/java/org/codice/ddf/admin/beta/enforcer/ArtifactSizeEnforcerRule.java
- artifact-size-enforcer/src/test/java/org/codice/ddf/admin/beta/enforcer/ArtifactSizeEnforcerRuleTest.java
- pom.xml
- query/graphql-dependencies/pom.xml
- query/graphql/pom.xml
- query/pom.xml
When the ArtifactSizeEnforceRule is active, it will look up the packaging type and enforce a maximum artifact size.
@coyotesqrl @djblue @adimka @peterhuffer @garrettfreibott 
Perform a clean install of the entire repo. Ensure any bundles are being enforced and any other types are not being enforced.
> DDF-2773: Created ArtifactSizeEnforcerRule to enforce artifact sizes

- security/ldap-config-handler/pom.xml
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/probe/DefaultDirectoryStructureProbe.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/probe/LdapQueryProbe.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/probe/SubjectAttributeProbe.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/AttributeMappingTestMethod.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/BindUserTestMethod.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/ConnectTestMethod.java
- security/ldap-config-handler/src/main/java/org/codice/ddf/admin/security/ldap/test/LdapTestingCommons.java
- security/ldap-config-handler/src/test/groovy/org/codice/ddf/admin/security/ldap/test/BindUserTestMethodTest.groovy
Fixes a few issues, most notably an LDAPConnectionFactory was not being closed and most LDAP connections were also unclosed.
Full build/test run.
It should be installed and LDAP should be tested to ensure it can still connect, bind, and query in the wizard.
N/A
N/A
> DDF-2773 Resolves several issues reported by SonarQube

- commons/pom.xml
- commons/src/main/java/org/codice/ddf/admin/commons/requests/RequestUtils.java
- commons/src/test/groovy/org.codice.ddf.admin.commons.requests/RequestUtilsTest.groovy
- federation/source-config-handlers/pom.xml
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceUtils.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/opensearch/persist/CreateOpenSearchSourcePersistMethod.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceConfigurationHandler.java
- federation/source-config-handlers/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceUtils.java
- federation/source-config-handlers/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- federation/source-config-handlers/src/test/groovy/org.codice.ddf.admin.sources/csw/CswSourceUtilsTest.groovy
- federation/source-config-handlers/src/test/groovy/org.codice.ddf.admin.sources/opensearch/OpenSearchSourceUtilsTest.groovy
- federation/source-config-handlers/src/test/groovy/org.codice.ddf.admin.sources/wfs/WfsSourceUtilsTest.groovy
- pom.xml
- ui/src/main/webapp/home/index.js
- ui/src/main/webapp/wizards/sources/stages/discovery.js
Swaps out the Apache HttpClient with a SecureCxfWebClient for source discovery. This allows discovery to function via the IdP auth method in DDF.
@peterhuffer @tbatie @coyotesqrl @stustison 
Full build, confirm all source types can be discovered when IdP is the default auth method.
This does require us to rely on a version of DDF that contains the changes I made to the SecureCxfClientFactory to facilitate generic web clients. I have this currently pointed at 2.11.0-SNAPSHOT which is 👎 . Once 2.10.2(3?) is released, we should point to that. I'm putting it up for now so we can review the rest of the code.
> DDF-2773 Replace HttpClient with security aware CXF client for source discovery

- configurator/configurator-api/src/main/java/org/codice/ddf/admin/configurator/ConfigReader.java
- configurator/configurator-impl/src/main/java/org/codice/ddf/admin/configurator/impl/ConfiguratorImpl.java
Adds a `getServices` method to the ConfigReader interface.
@coyotesqrl @tbatie 
We need to be able to get a list of services.
> DDF-2773: Add getServiceReferences to ConfigReader interface

- pom.xml
Disable the processing of the `repository.xml` file beneath Maven used by the maven bundle plugin.
@garrettfreibott @peterhuffer 
Travis build is sufficient
This improvement has been made to DDF and Alliance repositories already.
N/A
> DDF-2773 Disables OBR repository for the maven-bundle-plugin to speed up builds

- query/common/src/main/java/org/codice/ddf/admin/common/fields/base/BaseFunctionField.java
- query/security/wcpm/pom.xml
- query/security/wcpm/src/test/groovy/org/codice/ddf/admin/security/wcpm/persist/SaveContextPoliciesTest.groovy
- query/security/wcpm/src/test/groovy/org/codice/ddf/admin/security/wcpm/persist/SaveWhitelistContextsTest.groovy
- query/sources/impl/pom.xml
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/csw/CswFieldProviderTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/csw/discover/GetCswConfigsTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/csw/persist/DeleteCswConfigurationTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/csw/persist/SaveCswConfigurationTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/opensearch/OpenSearchFieldProviderTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/opensearch/discover/GetOpenSearchConfigsTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/opensearch/persist/DeleteOpenSearchConfigurationTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/opensearch/persist/SaveOpenSearchConfigurationTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/wfs/WfsFieldProviderTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/wfs/discover/GetWfsConfigsTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/wfs/persist/DeleteWfsConfigurationTest.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/wfs/persist/SaveWfsConfigurationTest.groovy
Reenables tests that had been ignored as part of the configurator refactor.
@peterhuffer @garrettfreibott 
Full CI run is sufficient
[DDF-2825](https://codice.atlassian.net/browse/DDF-2825)
N/A
> DDF-2825 Reenables unit tests

- ui/src/main/webapp/app.js
- ui/src/main/webapp/lib/ddf-sources/index.js
- ui/src/main/webapp/wizards/sources/graphql-mutations/source-persist.js
- ui/src/main/webapp/wizards/sources/graphql-queries/source-discovery.js
- ui/src/main/webapp/wizards/sources/index.js
Moves all queries, mutations, and configuration selectors to a map that gets passed into the sources wizard. This can allow for the simple addition of any more sources by adding new keys to the sources object.
@djblue 
@peterhuffer 
Make sure that everything still works. There should be no functional changes in the UI.
> Extensible Sources

- query/security/ldap/pom.xml
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapTestingUtils.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapQuerySpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestConnectionSpec.groovy
- query/security/ldap/src/test/java/org/codice/ddf/admin/ldap/TestLdapServer.java
Upgrades LDAP client libraries, fixes the startTLS extension so it correctly encrypts the connection over the LDAP port, and updates unit tests.
This also partially resolves the problem with MD5 bindings. _Iff_ the connection is secure, an MD5-bound connection will be able to negotiate and query LDAP. If it is not a secure connection, it cannot work with the default set of Quality of Protection (QoP) options.
We have two options:
1. If we decide that the MD5 binding is only supported over an encrypted channel; make validation and front-end changes to enforce that.
2. If we decide to allow MD5 binding over unencrypted channels, then we need to conditionally set the QoP options to only include `auth`. That change will need to be made both here and in DDF proper, as right now we do not …
> DDF-2773 Upgrades opendj libraries and fixes startTLS extension

- ui/src/main/webapp/wizards/sources/validation.js
- ui/src/main/webapp/wizards/sources/validation.spec.js
Previously, front end URL validation wasn't recognizing something like `https://somehost:8993/services/csw` as a valid URL. Add option to not require top level domains to URL validation method.
@djblue @tbatie @garrettfreibott
> DDF-2773: Fix front end URL validation

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapMessages.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestBind.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/connection/LdapBindUserInfo.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestBindSpec.groovy
- ui/src/main/webapp/lib/graphql-errors/index.js
Limits MD5 to be over encrypted LDAP connections.
Install KAR and then attempt to create an MD5 binding over an unencrypted LDAP connection. It should fail to pass.
N/A
> DDF-2773 Forces MD5 bindings to be over encrypted (LDAPS/startTLS) connections

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapMessages.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/LdapAttributeName.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/config/LdapDirectorySettingsField.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapAttributeNameSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettingsSpec.groovy
- ui/src/main/webapp/lib/graphql-errors/index.js
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
It validates user LDAP attributes and trows a USER_ATTRIBUTE_WRONG_FORMAT error instead of the Internal Error it use to display.
@coyotesqrl @peterhuffer @tbatie @djblue 
There are tests that were added and it can also be tested manually by going through the LDAP wizard.
The format of the attributes is based on RFC4519 and a manual test done before any changes were made.
> Validating the LDAP user attributes in directory settings and claims mapping

- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapQuerySpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestBindSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestConnectionSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapUserAttributesSpec.groovy
All LDAP unit tests that successfully open connections to the LDAP test server now have checks to ensure that the connections don't stay open.
@peterhuffer 
@tbatie  
@coyotesqrl 
Full build of `query/security/ldap` module passes.
> DDF-2773: Added Closed Connection Checks to LDAP Unit Tests

- query/graphql/src/main/java/org/codice/ddf/admin/graphql/servlet/ExtendedOsgiGraphQLServlet.java
- query/security/common/src/main/java/org/codice/ddf/admin/security/common/fields/ldap/LdapUseCase.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettings.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettingsSpec.groovy
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
Fixes LDAP directory settings test.
@tbatie 
@peterhuffer 
Unit tests and also run through the LDAP wizard making sure to hit the Authentication use case branch.
Previously the LDAP directory settings test was performing all checks 
independently of the use case, it has been updated to perform less checks 
when the use case is Authentication.
> DDF-2773 Fix ldap directory settings

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapServiceCommons.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/persist/CreateLdapConfiguration.java
Allow duplicate LDAP configurations by not validating if there is an existing one.
@coyotesqrl @tbatie @peterhuffer 
Going through the ldap wizard and seeing if you get the SIMILAR_SERVICE_EXISTS error (you shouldn't).
> DDF-2773 Allow duplicate LDAP configurations

- query/sources/common/src/main/java/org/codice/ddf/admin/sources/utils/RequestUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceUtils.java
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/csw/discover/DiscoverCswSourceSpec.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/opensearch/discover/DiscoverOpenSearchSpec.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/test/SourceCommonsSpec.groovy
- query/sources/impl/src/test/groovy/org/codice/ddf/admin/sources/wfs/discover/DiscoverWfsSourcesSpec.groovy
- Adds a builder for WebClients. This was needed so clients who need to specify special headers, encodings, etc can do so easily.
- Adjust unit tests to accommodate this change.
- Update some usages of `addResultMessage` in favor of `addArgumentMessage`
@tbatie @blen-desta 
Ensure that discovery of sources is still working as expected.
> DDF-2773 Add a builder for WebClients

- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
Fixes LDAP recommended settings query.
@tbatie 
Go though LDAP wizard ensuring the nothing broke and that the correct recommended setting query is sent.
When migrating the wizards to graphql, a mistake was made with the recommended settings query. This fix resolves that mistake.
> Fixed LDAP recommended settings query.

- query/common/src/main/java/org/codice/ddf/admin/common/PrioritizedBatchExecutor.java
Increases the default wait time for the `PrioritizedBatchExecutor` from 10 seconds to 60 seconds.
@tbatie @blen-desta @coyotesqrl 
> DDF-2773 Increase batch executor default time

- query/api/src/main/java/org/codice/ddf/admin/api/fields/ScalarField.java
- query/common/src/main/java/org/codice/ddf/admin/common/fields/base/scalar/BaseHiddenField.java
- query/common/src/main/java/org/codice/ddf/admin/common/fields/common/CredentialsField.java
- query/common/src/main/java/org/codice/ddf/admin/common/fields/common/PasswordField.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/servlet/ExtendedOsgiGraphQLServlet.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/FunctionDataFetcherException.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformOutput.java
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/transform/GraphQLTransformScalar.java
- query/graphql/src/test/groovy/org/codice/ddf/admin/graphql/test/FunctionDataFetcherExceptionTest.groovy
Passwords will be hidden in the logs.
@coyotesqrl @peterhuffer @tbatie 
Using graphiql send incorrect queries which will trigger an exception that will print the query. The password in that log should be replaced by `***`
> DDF-2773: Masking password in logs

- ui/package.json
- ui/yarn.lock
Flexbox-react was reverted to a version before it had a
dependency on styled-components in order to work with
the static site generator plugin.
Fixes the static html site that is first loaded to remove "flicker" effect.
@djblue 
Run `npm run dist` and open the generated index.html file. Make sure that on initial page load, the tile icons are centered in the tiles and that tile are not listed vertically.
> DDF-2773: Reverted Flexbox version to fix static styling issue

- query/common/src/main/java/org/codice/ddf/admin/common/report/message/DefaultMessages.java
- query/security/wcpm/src/main/java/org/codice/ddf/admin/security/wcpm/persist/SaveContextPolices.java
- query/security/wcpm/src/main/java/org/codice/ddf/admin/security/wcpm/persist/SaveWhitelistContexts.java
- query/security/wcpm/src/test/groovy/org/codice/ddf/admin/security/wcpm/persist/SaveContextPoliciesSpec.groovy
- query/security/wcpm/src/test/groovy/org/codice/ddf/admin/security/wcpm/persist/SaveWhitelistContextsTest.groovy
- ui/src/main/webapp/lib/graphql-errors/index.js
- ui/src/main/webapp/security/wcpm/policy.js
- ui/src/main/webapp/security/wcpm/validator.spec.js
- ui/src/main/webapp/security/wcpm/whitelist.js
AdminConsole WCPM not allow trailing slashes to context paths.
Added validations on the frontend and backend.
@coyotesqrl @peterhuffer @djblue
1- Unit tests
2- Going through the wizard and confirming that you can't add a whitelist context and/or a policy when there is a trailing slash in the context paths
> DDF-2773 AdminConsole WCPM not allow trailing slashes to context paths

- ui/package.json
- ui/yarn.lock
Bumps material-ui version to 0.19.1
@blen-desta 
Test that the attribute mapping stage no longer allows white space to be entered for the user attribute.
> Bump material-ui version to 0.19.1

- query/graphql/pom.xml
- query/graphql/src/main/java/org/codice/ddf/admin/graphql/servlet/ExtendedOsgiGraphQLServlet.java
- query/graphql/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Throttle GraphQL requests to prevent malicious use
* Uses the Jetty Dos Filter to do so
@coyotesqrl @tbatie @peterhuffer 
To test the DoS Filter,
1- Turn on jetty logs
- `log:set DEBUG org.eclipse.jetty.servlets` - DoS filter's logs
- `log:set DEBUG org.eclipse.jetty.servlet` - ServletHandler's logs (shows you the filter chains)
2- Set the `maxRequestsPerSec` and `throttledRequests` in graphql's blueprint to 1
3- Use the wizard, graphiql or (even better) ChrisB's script ([index.js.zip](https://github.com/connexta/admin-console-beta/files/1286337/index.js.zip)) to make 100 (or more) requests. I purposefully have an incorrect port to see the logs.
In the logs you should see:
- `call filter DoSFilter`
- `Filtering Request(POST https://localhost:8993/admin/hub/graphql)@39560d86`
- `Allowing …
> DDF-2773 Throttle GraphQL requests to prevent malicious use

- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
The following fields are not required when using LDAP only as an
authentication store.
- `memberAttributeReferencedInGroup`
- `groupObjectClass`
- `groupAttributeHoldingMember`
As such, they are now no longer being display when the user selects
`Authentication` as the LDAP use case. This fixes an issues intoduced by
the refactoring changes in `9005fb58bf6b64b90557ab90e0ba21fef1bc2c3e`.
@tbatie 
@oconnormi 
Try all three use cases in LDAP wizard ensuring that the aforementioned fields are hidden when being used for Authentication.
> Hide unused fields in LDAP wizard when not required.

- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.spec.js
Added unit tests to prevent regression of `<DirectorySettings />` stage in the LDAP wizard.
@tbatie 
@coyotesqrl 
`mvn clean install` ui directory.
> Added unit tests to the LDAP wizard.

- ui/src/main/webapp/security/wcpm/components.js
- ui/src/main/webapp/security/wcpm/policy.js
- ui/src/main/webapp/security/wcpm/validator.spec.js
- ui/webpack.config.js
The WCPM wizard's policies now have the delete button when they are being edited. It used to be on the bottom right corner of the page.
@garrettfreibott @blen-desta @djblue 
1. Build admin-console-beta
2. Build a downstream project. 
3. Go to the Admin UI, then to "setup". Click on the edit icon for a policy.
3. The Delete button should appear where the edit icon was.
4. Test the delete button works by
- Clicking on the button
- Clicking "No" on the confirmation
- Clicking "Yes" on the confirmation (should delete policy)
- Clicking "Yes" on the Policy where the **Context Path** is `/`. This policy should not be able to delete from WCPM. 
5. Test this for Chrome, Firefox, and IE
> DDF-3353 Delete buttons in the WCPM wizard appear in the policy they are meant to delete

- query/security/common/src/main/java/org/codice/ddf/admin/security/common/services/LdapLoginServiceProperties.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapServiceCommons.java
Adds an additional field to the LDAP authentication configuration
@tbatie @coyotesqrl 
[DDF-3328](https://codice.atlassian.net/browse/DDF-3328)
> DDF-3328 Update LDAP login configuration to separate the user attributes for group membership and login

- query/security/common/src/main/java/org/codice/ddf/admin/security/common/services/LdapLoginServiceProperties.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapServiceCommons.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/ServerGuesser.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/config/LdapDirectorySettingsField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/query/LdapRecommendedSettingsField.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/CreateLdapConfigurationSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettingsSpec.groovy
- query/security/ldap/src/test/java/org/codice/ddf/admin/ldap/LdapTestingCommons.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/AdminSecurityIT.java
- tests/itests/src/test/resources/query/ldap/query/GetLdapConfigs.graphql
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.spec.js
Updates the LDAP wizard to be consistent with the Security STS LDAP Login configuration and the Security STS LDAP and Roles Claims Handler configuration.
@coyotesqrl 
@tbatie 
@peterhuffer 
@djblue 
- Use the LDAP Wizard to setup various LDAP configurations.
- Verify that the configurations are persisted using the Admin UI.
- Verify that the configurations can be fetched using Graphiql
**graphiql query**
```{
ldap {
configs {
pid
directorySettings {
loginUserAttribute
baseUserDn
baseGroupDn
groupObjectClass
groupAttributeHoldingMember
memberAttributeReferencedInGroup
useCase
}
}
}
}
```
> Update LDAP wizard to use new DDF config

- query/security/common/src/main/java/org/codice/ddf/admin/security/common/services/LdapLoginServiceProperties.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapServiceCommons.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/ServerGuesser.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/config/LdapDirectorySettingsField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/query/LdapRecommendedSettingsField.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/CreateLdapConfigurationSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappingsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettingsSpec.groovy
- query/security/ldap/src/test/java/org/codice/ddf/admin/ldap/LdapTestingCommons.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/AdminSecurityIT.java
- tests/itests/src/test/resources/query/ldap/query/GetLdapConfigs.graphql
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.spec.js
Backport of [PR #171](https://github.com/connexta/admin-console/pull/171).  Updates the LDAP wizard to be consistent with the Security STS LDAP Login configuration and the Security STS LDAP and Roles Claims Handler configuration.
@tbatie 
- Use the LDAP Wizard to setup various LDAP configurations.
- Verify that the configurations are persisted using the Admin UI.
- Verify that the configurations can be fetched using Graphiql
**graphiql query**
```{
ldap {
configs {
pid
directorySettings {
loginUserAttribute
baseUserDn
baseGroupDn
groupObjectClass
groupAttributeHoldingMember
memberAttributeReferencedInGroup
useCase
}
}
}
}
```
> [1.1.x] Update LDAP wizard to use new DDF config

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapQuery.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestBind.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestConnection.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapUserAttributes.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/discover/DiscoverCswSource.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/discover/DiscoverOpenSearchSource.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/wfs/discover/DiscoverWfsSource.java
Back port of https://github.com/connexta/admin-console/pull/172
Changed `@VisibleForTestingAnnotation` to `@SuppressWarnings(
"squid:UnusedPrivateMethod" /* For testing purposes only. Groovy can access private methods. */)`
@coyotesqrl @tbatie @peterhuffer 
Full build
> [1.1.x] DDF-2773 Changed @VisibleForTestingAnnotation to a suppression

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapQuery.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestBind.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestClaimMappings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestConnection.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapUserAttributes.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/CswSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/csw/discover/DiscoverCswSource.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/OpenSearchSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/opensearch/discover/DiscoverOpenSearchSource.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/wfs/WfsSourceUtils.java
- query/sources/impl/src/main/java/org/codice/ddf/admin/sources/wfs/discover/DiscoverWfsSource.java
Changed `@VisibleForTestingAnnotation` to `@SuppressWarnings(
"squid:UnusedPrivateMethod" /* For testing purposes only. Groovy can access private methods. */)`
@coyotesqrl @tbatie @peterhuffer 
Full build
> DDF-2773 Changed @VisibleForTestingAnnotation to a suppression

- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
This PR fixes an issue of allowing invalid Port numbers in the LDAP Wizard.
This PR is still a WIP. I need to discuss the solution with SMEs.
@djblue @peterhuffer @garrettfreibott 
In the LDAP Wizard enter an invalid port number. Confirm that there is an error message.
The Sources Wizard also does this Port validation on the front end: 
https://github.com/connexta/admin-console/blob/9005fb58bf6b64b90557ab90e0ba21fef1bc2c3e/ui/src/main/webapp/wizards/sources/stages/validation.js#L44-L46 https://github.com/connexta/admin-console/blob/9005fb58bf6b64b90557ab90e0ba21fef1bc2c3e/ui/src/main/webapp/wizards/sources/stages/discovery.js#L68-L73
> [1.1.x] DDF-2773 Added port validation in the LDAP Wizard before submitting GraphQL query

- ui/src/main/webapp/lib/admin-wizard/enhancers.js
Sets empty string values to null and prevents users from entering values with leading whitespace. 
@tbatie @peterhuffer @blen-desta @garrettfreibott  
On LDAP Bind User Settings page, select `DigestMD5SASL` as Bind User Method, attempt to enter empty string value for the realm and click next. `Missing required field.` error should appear instead of `Empty required field`. Now select `Simple` as the Bind User Method and click next. The LDAP Directory Structure page should appear. 
Prior to this change, empty string values would throw `Empty required field.` errors on optional string fields. This caused a hidden error when clearing out the realm prior to continuing with the `Simple` Bind User Method.
> Prevents requests with empty string from being sent to backend

- ui/src/main/webapp/lib/static-site-generator/html.js
See title.
@tbatie 
@andrewkfiedler 
- quick build
- deploy
- ensure ui works in an iframe
When we [collapse the ui modules](https://github.com/codice/ddf/pull/2911), all the webjars will be served from the `/webjars` path. This fix updates the script to point to the new location.
[DDF-3584](https://codice.atlassian.net/browse/DDF-3584)
> DDF-3584 Updates index.html to use `/webjars` endpoint

- pom.xml
This PR bumps the DDF version to 2.12.0.
@tbatie @coyotesqrl @peterhuffer 
Build a release of a project that includes admin-console, and confirm that the Wizards still work.
The admin-console repo needed to be updated after the feature file rework (a83ee624a13c410bf3ebbea09443885c10e7c9e4), so it should be building with the latest DDF version.
> DDF-2773 Bumped DDF version to 2.12.0

- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/persist/CreateLdapConfiguration.java
- query/sources/common/src/main/java/org/codice/ddf/admin/sources/utils/RequestUtils.java
Adds privileged actions to the RequestUtils for the Sources wizard and to the LDAP wizard to be able to read/write the generated LDAP config file.
@tbatie @emmberk @coyotesqrl 
With security manager enabled, ensure sources can be discovered and saved, and that LDAP configurations can be configured and saved. Test creating a new policy as well.
This is a temporary solution until privileged actions are added to the configurator in DDF 2.13.0.
> DDF-2773 Add privileged actions to LDAP and Source wizards

- query/security/common/src/main/java/org/codice/ddf/admin/security/common/services/LdapClaimsHandlerServiceProperties.java
- query/security/common/src/main/java/org/codice/ddf/admin/security/common/services/LdapLoginServiceProperties.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapServiceCommons.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/ServerGuesser.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/config/LdapConfigurationField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/connection/LdapConnectionField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/connection/LdapLoadBalancingField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/persist/CreateLdapConfiguration.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/CreateLdapConfigurationSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/GetLdapConfigurationsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettingsSpec.groovy
- query/security/ldap/src/test/java/org/codice/ddf/admin/ldap/LdapTestingCommons.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/AdminSecurityIT.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/request/LdapRequestHelper.java
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
- ui/src/main/webapp/wizards/ldap/stages/bind-settings.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.spec.js
- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
Remove LDAP structure assumptions, provide better default values, enable LDAP login and attribute claims to work with nested user OUs, allow multiple ldap servers in a single configuration for load balancing / failover.
This is a companion PR to this [DDF-4090 PR](https://github.com/codice/ddf/pull/3665)
@tbatie 
@stustison 
@peterhuffer 
@djblue 
This needs to be built and deployed with this [DDF-4090 PR](https://github.com/codice/ddf/pull/3665).
Create or setup two identical LDAP servers (can be on the same machine if using different ports):
Create a user in a nested OU under the base user DN
Set their uid and cn to be different values (e.g. uid=user1, cn=User One)
Add the user to a group with uid as the member attribute in the group reference
Repeat for another user but utilize cn as …
> [1.2.x] DDF-4090 - Remove LDAP assumptions and allow multiple hosts in single configuration

- query/security/common/src/main/java/org/codice/ddf/admin/security/common/services/LdapClaimsHandlerServiceProperties.java
- query/security/common/src/main/java/org/codice/ddf/admin/security/common/services/LdapLoginServiceProperties.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/LdapServiceCommons.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/commons/ServerGuesser.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/discover/LdapTestDirectorySettings.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/config/LdapConfigurationField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/connection/LdapConnectionField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/fields/connection/LdapLoadBalancingField.java
- query/security/ldap/src/main/java/org/codice/ddf/admin/ldap/persist/CreateLdapConfiguration.java
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/CreateLdapConfigurationSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/GetLdapConfigurationsSpec.groovy
- query/security/ldap/src/test/groovy/org/codice/ddf/admin/ldap/discover/LdapRecommendedSettingsSpec.groovy
- query/security/ldap/src/test/java/org/codice/ddf/admin/ldap/LdapTestingCommons.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/AdminSecurityIT.java
- tests/itests/src/test/java/org/codice/ddf/admin/query/request/LdapRequestHelper.java
- ui/src/main/webapp/wizards/ldap/stages/attribute-mapping.js
- ui/src/main/webapp/wizards/ldap/stages/bind-settings.js
- ui/src/main/webapp/wizards/ldap/stages/confirm.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.js
- ui/src/main/webapp/wizards/ldap/stages/directory-settings.spec.js
- ui/src/main/webapp/wizards/ldap/stages/network-settings.js
ABBREVIATED REVIEW BETWEEN 1.2.X AND MASTER
Link to 1.2.x PR: [#212](https://github.com/connexta/admin-console/pull/212)
Remove LDAP structure assumptions, provide better default values, enable LDAP login and attribute claims to work with nested user OUs, allow multiple ldap servers in a single configuration for load balancing / failover.
This is a companion PR to this [DDF-4090 PR](https://github.com/codice/ddf/pull/3767)
@coyotesqrl 
@tbatie
@stustison
@peterhuffer
@djblue
This needs to be built and deployed with this [DDF-4090 PR](https://github.com/codice/ddf/pull/3767).
Create or setup two identical LDAP servers (can be on the same machine if using different ports):
Create a user in a nested OU under the base user DN
Set their uid and cn to be different values (e.g. uid=user1, …
> DDF-4090 Remove LDAP assumptions and allow multiple hosts in single configuration

- Jenkinsfile
- pom.xml
- Removes the `nsp check` since the Node Security Platform is no longer available. This causes a network error during the security checks.
- Ignore GIB failures to prevent build from failing. If GIB cannot calculate what to build, default will go back to full build of PR.
@coyotesqrl @oconnormi 
Full build.
See: https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting
> Fix pipeline due to unavailable service

- pom.xml
- query/app/src/main/resources/features.xml
- query/sources/common/pom.xml
Update dependencies since catalog-core-api no longer supplies them.
Fix admin-query-sources-impl install
@peterhuffer @tbatie 
I will let Peter and Tracy decide that.
This is a port from master
> DDF-2985 Declare transitive dependencies no longer available in catalog-core-api

- pom.xml
- Replaces spock-shaded with spock-all.
- Upgrade jacoco-maven-plugin
@coyotesqrl @tbatie @clockard @brjeter 
Full build.
N/A
> Fix missing spock dependency

- pom.xml
- tests/itests/pom.xml
- tests/pom.xml
Updates to DDF version 2.15.0-SNAPSHOT and updates the spock dependencies. Without this, downstream projects are starting duplicates of both 2.14.0-SNAPSHOT and 2.15.0-SNAPSHOT.
@peterhuffer @emmberk
> Updated DDF to 2.15.0-SNAPSHOT

- pom.xml
The nightly build is currently breaking on OWASP. This fixes the OWASP configuration to point to the local NVD db.
```
[2019-06-16T02:47:44.049Z] [ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.0.2:aggregate (aggregation) on project admin: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during dependency-check analysis
[2019-06-16T02:47:44.049Z] [ERROR]     The download was interrupted; unable to complete the update
[2019-06-16T02:47:44.049Z] [ERROR] -> [Help 1]
[2019-06-16T02:47:44.049Z] [ERROR] 
[2019-06-16T02:47:44.049Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[2019-06-16T02:47:44.049Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging. …
```
> Point to the local NVD server for OWASP

- features/admin-query/pom.xml
- features/admin-query/src/main/feature/feature.xml
- features/dev/pom.xml
- features/dev/src/main/feature/feature.xml
- features/testing/pom.xml
- features/testing/src/main/feature/feature.xml
Removes DDF feature repos and disables the feature itests until we can upgrade Karaf. See #246 for details.
@peterhuffer @blen-desta 
CI
Hero steps:
- Build admin-console on this PR
- Point downstream project to admin-console version `1.3.1-SNAPSHOT` and ddf version `2.16.0-SNAPSHOT`
- Build the downstream project
- Run and install the downstream project.
- Either tail the logs are do a `list -t 0 -s | grep -i ddf` every once in awhile, and make sure no `2.15.0` versioned DDF bundles are starting up.
> Remove DDF feature repos temporarily
